### ISSUE TITLE
`maturin develop` does not copy/move dylib dependencies in Cargo target directory

### ISSUE THREAD

**Issue by messense** [PyO3/maturin#1093]
Actually maybe I spoke too soon - `maturin build --release` builds a wheel that properly includes the library and installs just fine. `maturin develop` however does not seem to move the library to wherever python is looking for it. Was this fix expected to address `develop` too?

_Originally posted by @jdiggans-twist in https://github.com/PyO3/maturin/issues/1088#issuecomment-1242250172_

---

After #1092 `maturin build` correctly packages dylib dependencies in Cargo target directory, but for `maturin develop` we only copy the Python extension module `.so` file not its dylib dependencies in Cargo target directory which might cause `ImportError` when try to `import` the extension module.

```bash
(venv) [root@a3493c3871fc maturin]# cargo run dev -m ../dylib-target/Cargo.toml
    Finished dev [unoptimized + debuginfo] target(s) in 1.30s
     Running `target/debug/maturin dev -m ../dylib-target/Cargo.toml`
🔗 Found pyo3 bindings
🐍 Found CPython 3.10 at /io/maturin/venv/bin/python
   Compiling pyo3-build-config v0.17.1
   Compiling pyo3-ffi v0.17.1
   Compiling pyo3 v0.17.1
   Compiling dylib-target v0.1.0 (/io/dylib-target)
    Finished dev [unoptimized + debuginfo] target(s) in 22.03s
📦 Built wheel for CPython 3.10 to /tmp/.tmpuXUpqH/dylib_target-0.1.0-cp310-cp310-linux_x86_64.whl
🛠  Installed dylib-target-0.1.0
(venv) [root@a3493c3871fc maturin]# python3
Python 3.10.7 (main, Sep  7 2022, 22:31:23) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dylib_target
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/io/maturin/venv/lib/python3.10/site-packages/dylib_target/__init__.py", line 1, in <module>
    from .dylib_target import *
ImportError: libcatboostmodel.so.1: cannot open shared object file: No such file or directory
```

**Comment by messense** [comment]
@jdiggans-twist Please try v0.13.3-beta.4, you can install it by running `pip install maturin==0.13.3b4`.
