### ISSUE TITLE
Make sure tests pass when running with PyPy

### ISSUE THREAD

**Issue by messense** [PyO3/maturin#1219]
- [x] https://github.com/PyO3/maturin/pull/1218
- [x] `cargo test` with CPython then with PyPy should succeed, fixed by #1220 
- [x] `cargo test` with PyPy then with CPython should succeed, fixed by #1220

**Comment by messense** [comment]
> cargo test with PyPy then with CPython should succeed

Current status on Ubuntu 22.04, `MATURIN_TEST_PYTHON=pypy3 cargo test` passes, `cargo test` fails without cleaning build artifacts from previous build

```bash
$ cargo test
...
failures:

---- develop_pyo3_mixed_py_subdir stdout ----
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings
🐍 Found CPython 3.10 at /root/code/maturin/test-crates/venvs/develop-pyo3-mixed-py-subdir/bin/python
📦 Built wheel for CPython 3.10 to /tmp/.tmpIBORRt/pyo3_mixed_py_subdir-2.1.3-cp310-cp310-linux_x86_64.whl
🛠  Installed pyo3-mixed-py-subdir-2.1.3
Cause: Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "/root/code/maturin/test-crates/pyo3-mixed-py-subdir/check_installed/check_installed.py", line 3, in <module>
    import pyo3_mixed_py_subdir as pyo3_mixed
  File "/root/code/maturin/test-crates/pyo3-mixed-py-subdir/python/pyo3_mixed_py_subdir/__init__.py", line 2, in <module>
    from ._pyo3_mixed import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed-py-subdir/python/pyo3_mixed_py_subdir/_pyo3_mixed.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyPyUnicode_AsUTF8AndSize

thread 'develop_pyo3_mixed_py_subdir' panicked at 'Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "/root/code/maturin/test-crates/pyo3-mixed-py-subdir/check_installed/check_installed.py", line 3, in <module>
    import pyo3_mixed_py_subdir as pyo3_mixed
  File "/root/code/maturin/test-crates/pyo3-mixed-py-subdir/python/pyo3_mixed_py_subdir/__init__.py", line 2, in <module>
    from ._pyo3_mixed import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed-py-subdir/python/pyo3_mixed_py_subdir/_pyo3_mixed.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyPyUnicode_AsUTF8AndSize
', tests/common/mod.rs:89:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- develop_pyo3_mixed_src_layout stdout ----
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings
🐍 Found CPython 3.10 at /root/code/maturin/test-crates/venvs/develop-pyo3-mixed-src/bin/python
📦 Built wheel for CPython 3.10 to /tmp/.tmpmTJ1iB/pyo3_mixed_src-2.1.3-cp310-cp310-linux_x86_64.whl
🛠  Installed pyo3-mixed-src-2.1.3
Cause: Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "/root/code/maturin/test-crates/pyo3-mixed-src/check_installed/check_installed.py", line 3, in <module>
    import pyo3_mixed_src as pyo3_mixed
  File "/root/code/maturin/test-crates/pyo3-mixed-src/src/pyo3_mixed_src/__init__.py", line 2, in <module>
    from .pyo3_mixed_src import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed-src/src/pyo3_mixed_src/pyo3_mixed_src.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyPyUnicode_AsUTF8AndSize

thread 'develop_pyo3_mixed_src_layout' panicked at 'Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "/root/code/maturin/test-crates/pyo3-mixed-src/check_installed/check_installed.py", line 3, in <module>
    import pyo3_mixed_src as pyo3_mixed
  File "/root/code/maturin/test-crates/pyo3-mixed-src/src/pyo3_mixed_src/__init__.py", line 2, in <module>
    from .pyo3_mixed_src import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed-src/src/pyo3_mixed_src/pyo3_mixed_src.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyPyUnicode_AsUTF8AndSize
', tests/common/mod.rs:89:13

---- develop_pyo3_mixed stdout ----
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings
🐍 Found CPython 3.10 at /root/code/maturin/test-crates/venvs/develop-pyo3-mixed/bin/python
📦 Built wheel for CPython 3.10 to /tmp/.tmp76MhOA/pyo3_mixed-2.1.3-cp310-cp310-linux_x86_64.whl
🛠  Installed pyo3-mixed-2.1.3
Cause: Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "/root/code/maturin/test-crates/pyo3-mixed/check_installed/check_installed.py", line 4, in <module>
    import pyo3_mixed
  File "/root/code/maturin/test-crates/pyo3-mixed/pyo3_mixed/__init__.py", line 2, in <module>
    from .pyo3_mixed import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed/pyo3_mixed/pyo3_mixed.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyPyUnicode_AsUTF8AndSize

thread 'develop_pyo3_mixed' panicked at 'Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "/root/code/maturin/test-crates/pyo3-mixed/check_installed/check_installed.py", line 4, in <module>
    import pyo3_mixed
  File "/root/code/maturin/test-crates/pyo3-mixed/pyo3_mixed/__init__.py", line 2, in <module>
    from .pyo3_mixed import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed/pyo3_mixed/pyo3_mixed.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyPyUnicode_AsUTF8AndSize
', tests/common/mod.rs:89:13

---- develop_pyo3_mixed_submodule stdout ----
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings
🐍 Found CPython 3.10 at /root/code/maturin/test-crates/venvs/develop-pyo3-mixed-submodule/bin/python
📦 Built wheel for CPython 3.10 to /tmp/.tmpReQyfk/pyo3_mixed_submodule-2.1.3-cp310-cp310-linux_x86_64.whl
🛠  Installed pyo3-mixed-submodule-2.1.3
Cause: Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "/root/code/maturin/test-crates/pyo3-mixed-submodule/check_installed/check_installed.py", line 3, in <module>
    import pyo3_mixed_submodule
  File "/root/code/maturin/test-crates/pyo3-mixed-submodule/pyo3_mixed_submodule/__init__.py", line 2, in <module>
    from .rust_module.rust import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed-submodule/pyo3_mixed_submodule/rust_module/rust.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyPyUnicode_AsUTF8AndSize

thread 'develop_pyo3_mixed_submodule' panicked at 'Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "/root/code/maturin/test-crates/pyo3-mixed-submodule/check_installed/check_installed.py", line 3, in <module>
    import pyo3_mixed_submodule
  File "/root/code/maturin/test-crates/pyo3-mixed-submodule/pyo3_mixed_submodule/__init__.py", line 2, in <module>
    from .rust_module.rust import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed-submodule/pyo3_mixed_submodule/rust_module/rust.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyPyUnicode_AsUTF8AndSize
', tests/common/mod.rs:89:13

---- editable_pyo3_mixed_py_subdir stdout ----
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings
🐍 Found CPython 3.10 at /root/code/maturin/test-crates/venvs/editable-pyo3-mixed-py-subdir/bin/python
📦 Built wheel for CPython 3.10 to test-crates/wheels/editable-pyo3-mixed-py-subdir/pyo3_mixed_py_subdir-2.1.3-cp310-cp310-linux_x86_64.whl
Cause: Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "/root/code/maturin/test-crates/pyo3-mixed-py-subdir/check_installed/check_installed.py", line 3, in <module>
    import pyo3_mixed_py_subdir as pyo3_mixed
  File "/root/code/maturin/test-crates/pyo3-mixed-py-subdir/python/pyo3_mixed_py_subdir/__init__.py", line 2, in <module>
    from ._pyo3_mixed import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed-py-subdir/python/pyo3_mixed_py_subdir/_pyo3_mixed.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyPyUnicode_AsUTF8AndSize

thread 'editable_pyo3_mixed_py_subdir' panicked at 'Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "/root/code/maturin/test-crates/pyo3-mixed-py-subdir/check_installed/check_installed.py", line 3, in <module>
    import pyo3_mixed_py_subdir as pyo3_mixed
  File "/root/code/maturin/test-crates/pyo3-mixed-py-subdir/python/pyo3_mixed_py_subdir/__init__.py", line 2, in <module>
    from ._pyo3_mixed import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed-py-subdir/python/pyo3_mixed_py_subdir/_pyo3_mixed.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyPyUnicode_AsUTF8AndSize
', tests/common/mod.rs:89:13

---- editable_pyo3_mixed stdout ----
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings
🐍 Found CPython 3.10 at /root/code/maturin/test-crates/venvs/editable-pyo3-mixed/bin/python
📦 Built wheel for CPython 3.10 to test-crates/wheels/editable-pyo3-mixed/pyo3_mixed-2.1.3-cp310-cp310-linux_x86_64.whl
Cause: Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "/root/code/maturin/test-crates/pyo3-mixed/check_installed/check_installed.py", line 4, in <module>
    import pyo3_mixed
  File "/root/code/maturin/test-crates/pyo3-mixed/pyo3_mixed/__init__.py", line 2, in <module>
    from .pyo3_mixed import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed/pyo3_mixed/pyo3_mixed.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyPyUnicode_AsUTF8AndSize

thread 'editable_pyo3_mixed' panicked at 'Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "/root/code/maturin/test-crates/pyo3-mixed/check_installed/check_installed.py", line 4, in <module>
    import pyo3_mixed
  File "/root/code/maturin/test-crates/pyo3-mixed/pyo3_mixed/__init__.py", line 2, in <module>
    from .pyo3_mixed import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed/pyo3_mixed/pyo3_mixed.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyPyUnicode_AsUTF8AndSize
', tests/common/mod.rs:89:13


failures:
    develop_pyo3_mixed
    develop_pyo3_mixed_py_subdir
    develop_pyo3_mixed_src_layout
    develop_pyo3_mixed_submodule
    editable_pyo3_mixed
    editable_pyo3_mixed_py_subdir

test result: FAILED. 32 passed; 6 failed; 0 ignored; 0 measured; 0 filtered out; finished in 133.64s

error: test failed, to rerun pass '--test run'
```

**Comment by messense** [comment]
> cargo test with CPython then with PyPy should succeed

Current status on Ubuntu 22.04, `cargo test` passes, `MATURIN_TEST_PYTHON=pypy3 cargo test` fails without cleaning build artifacts from previous build

```bash
$ MATURIN_TEST_PYTHON=pypy3 cargo test
...
failures:

---- develop_pyo3_mixed_py_subdir stdout ----
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings
🐍 Found PyPy 3.8 at /root/code/maturin/test-crates/venvs/develop-pyo3-mixed-py-subdir/bin/python
📦 Built wheel for PyPy 3.8 to /tmp/.tmpC5OFtq/pyo3_mixed_py_subdir-2.1.3-pp38-pypy38_pp73-linux_x86_64.whl
🛠  Installed pyo3-mixed-py-subdir-2.1.3
Cause: Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "test-crates/pyo3-mixed-py-subdir/check_installed/check_installed.py", line 3, in <module>
    import pyo3_mixed_py_subdir as pyo3_mixed
  File "/root/code/maturin/test-crates/pyo3-mixed-py-subdir/python/pyo3_mixed_py_subdir/__init__.py", line 2, in <module>
    from ._pyo3_mixed import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed-py-subdir/python/pyo3_mixed_py_subdir/_pyo3_mixed.pypy38-pp73-x86_64-linux-gnu.so: undefined symbol: PyExc_BaseException

thread 'develop_pyo3_mixed_py_subdir' panicked at 'Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "test-crates/pyo3-mixed-py-subdir/check_installed/check_installed.py", line 3, in <module>
    import pyo3_mixed_py_subdir as pyo3_mixed
  File "/root/code/maturin/test-crates/pyo3-mixed-py-subdir/python/pyo3_mixed_py_subdir/__init__.py", line 2, in <module>
    from ._pyo3_mixed import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed-py-subdir/python/pyo3_mixed_py_subdir/_pyo3_mixed.pypy38-pp73-x86_64-linux-gnu.so: undefined symbol: PyExc_BaseException
', tests/common/mod.rs:89:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- develop_pyo3_mixed_src_layout stdout ----
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings
🐍 Found PyPy 3.8 at /root/code/maturin/test-crates/venvs/develop-pyo3-mixed-src/bin/python
📦 Built wheel for PyPy 3.8 to /tmp/.tmp5OWEgv/pyo3_mixed_src-2.1.3-pp38-pypy38_pp73-linux_x86_64.whl
🛠  Installed pyo3-mixed-src-2.1.3
Cause: Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "test-crates/pyo3-mixed-src/check_installed/check_installed.py", line 3, in <module>
    import pyo3_mixed_src as pyo3_mixed
  File "/root/code/maturin/test-crates/pyo3-mixed-src/src/pyo3_mixed_src/__init__.py", line 2, in <module>
    from .pyo3_mixed_src import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed-src/src/pyo3_mixed_src/pyo3_mixed_src.pypy38-pp73-x86_64-linux-gnu.so: undefined symbol: PyExc_BaseException

thread 'develop_pyo3_mixed_src_layout' panicked at 'Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "test-crates/pyo3-mixed-src/check_installed/check_installed.py", line 3, in <module>
    import pyo3_mixed_src as pyo3_mixed
  File "/root/code/maturin/test-crates/pyo3-mixed-src/src/pyo3_mixed_src/__init__.py", line 2, in <module>
    from .pyo3_mixed_src import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed-src/src/pyo3_mixed_src/pyo3_mixed_src.pypy38-pp73-x86_64-linux-gnu.so: undefined symbol: PyExc_BaseException
', tests/common/mod.rs:89:13

---- develop_pyo3_mixed_submodule stdout ----
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings
🐍 Found PyPy 3.8 at /root/code/maturin/test-crates/venvs/develop-pyo3-mixed-submodule/bin/python
📦 Built wheel for PyPy 3.8 to /tmp/.tmpxoU7ba/pyo3_mixed_submodule-2.1.3-pp38-pypy38_pp73-linux_x86_64.whl
🛠  Installed pyo3-mixed-submodule-2.1.3
Cause: Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "test-crates/pyo3-mixed-submodule/check_installed/check_installed.py", line 3, in <module>
    import pyo3_mixed_submodule
  File "/root/code/maturin/test-crates/pyo3-mixed-submodule/pyo3_mixed_submodule/__init__.py", line 2, in <module>
    from .rust_module.rust import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed-submodule/pyo3_mixed_submodule/rust_module/rust.pypy38-pp73-x86_64-linux-gnu.so: undefined symbol: PyExc_BaseException

thread 'develop_pyo3_mixed_submodule' panicked at 'Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "test-crates/pyo3-mixed-submodule/check_installed/check_installed.py", line 3, in <module>
    import pyo3_mixed_submodule
  File "/root/code/maturin/test-crates/pyo3-mixed-submodule/pyo3_mixed_submodule/__init__.py", line 2, in <module>
    from .rust_module.rust import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed-submodule/pyo3_mixed_submodule/rust_module/rust.pypy38-pp73-x86_64-linux-gnu.so: undefined symbol: PyExc_BaseException
', tests/common/mod.rs:89:13

---- develop_pyo3_mixed stdout ----
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings
🐍 Found PyPy 3.8 at /root/code/maturin/test-crates/venvs/develop-pyo3-mixed/bin/python
📦 Built wheel for PyPy 3.8 to /tmp/.tmptz08FW/pyo3_mixed-2.1.3-pp38-pypy38_pp73-linux_x86_64.whl
🛠  Installed pyo3-mixed-2.1.3
Cause: Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "test-crates/pyo3-mixed/check_installed/check_installed.py", line 4, in <module>
    import pyo3_mixed
  File "/root/code/maturin/test-crates/pyo3-mixed/pyo3_mixed/__init__.py", line 2, in <module>
    from .pyo3_mixed import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed/pyo3_mixed/pyo3_mixed.pypy38-pp73-x86_64-linux-gnu.so: undefined symbol: PyExc_BaseException

thread 'develop_pyo3_mixed' panicked at 'Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "test-crates/pyo3-mixed/check_installed/check_installed.py", line 4, in <module>
    import pyo3_mixed
  File "/root/code/maturin/test-crates/pyo3-mixed/pyo3_mixed/__init__.py", line 2, in <module>
    from .pyo3_mixed import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed/pyo3_mixed/pyo3_mixed.pypy38-pp73-x86_64-linux-gnu.so: undefined symbol: PyExc_BaseException
', tests/common/mod.rs:89:13

---- editable_pyo3_mixed_py_subdir stdout ----
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings
🐍 Found PyPy 3.8 at /root/code/maturin/test-crates/venvs/editable-pyo3-mixed-py-subdir/bin/python
📦 Built wheel for PyPy 3.8 to test-crates/wheels/editable-pyo3-mixed-py-subdir/pyo3_mixed_py_subdir-2.1.3-pp38-pypy38_pp73-linux_x86_64.whl
Cause: Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "test-crates/pyo3-mixed-py-subdir/check_installed/check_installed.py", line 3, in <module>
    import pyo3_mixed_py_subdir as pyo3_mixed
  File "/root/code/maturin/test-crates/pyo3-mixed-py-subdir/python/pyo3_mixed_py_subdir/__init__.py", line 2, in <module>
    from ._pyo3_mixed import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed-py-subdir/python/pyo3_mixed_py_subdir/_pyo3_mixed.pypy38-pp73-x86_64-linux-gnu.so: undefined symbol: PyExc_BaseException

thread 'editable_pyo3_mixed_py_subdir' panicked at 'Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "test-crates/pyo3-mixed-py-subdir/check_installed/check_installed.py", line 3, in <module>
    import pyo3_mixed_py_subdir as pyo3_mixed
  File "/root/code/maturin/test-crates/pyo3-mixed-py-subdir/python/pyo3_mixed_py_subdir/__init__.py", line 2, in <module>
    from ._pyo3_mixed import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed-py-subdir/python/pyo3_mixed_py_subdir/_pyo3_mixed.pypy38-pp73-x86_64-linux-gnu.so: undefined symbol: PyExc_BaseException
', tests/common/mod.rs:89:13

---- editable_pyo3_mixed stdout ----
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings
🐍 Found PyPy 3.8 at /root/code/maturin/test-crates/venvs/editable-pyo3-mixed/bin/python
📦 Built wheel for PyPy 3.8 to test-crates/wheels/editable-pyo3-mixed/pyo3_mixed-2.1.3-pp38-pypy38_pp73-linux_x86_64.whl
Cause: Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "test-crates/pyo3-mixed/check_installed/check_installed.py", line 4, in <module>
    import pyo3_mixed
  File "/root/code/maturin/test-crates/pyo3-mixed/pyo3_mixed/__init__.py", line 2, in <module>
    from .pyo3_mixed import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed/pyo3_mixed/pyo3_mixed.pypy38-pp73-x86_64-linux-gnu.so: undefined symbol: PyExc_BaseException

thread 'editable_pyo3_mixed' panicked at 'Check install fail: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "test-crates/pyo3-mixed/check_installed/check_installed.py", line 4, in <module>
    import pyo3_mixed
  File "/root/code/maturin/test-crates/pyo3-mixed/pyo3_mixed/__init__.py", line 2, in <module>
    from .pyo3_mixed import get_21
ImportError: /root/code/maturin/test-crates/pyo3-mixed/pyo3_mixed/pyo3_mixed.pypy38-pp73-x86_64-linux-gnu.so: undefined symbol: PyExc_BaseException
', tests/common/mod.rs:89:13


failures:
    develop_pyo3_mixed
    develop_pyo3_mixed_py_subdir
    develop_pyo3_mixed_src_layout
    develop_pyo3_mixed_submodule
    editable_pyo3_mixed
    editable_pyo3_mixed_py_subdir

test result: FAILED. 32 passed; 6 failed; 0 ignored; 0 measured; 0 filtered out; finished in 138.30s

error: test failed, to rerun pass '--test run'
```

Looks like they are all related to mixed Rust/Python layout when installed as editable.

**Comment by messense** [comment]
My guess is that `PYO3_PYTHON` env var passed to pyo3 is the same while the virtualenv is recreated, thus `pyo3-build-config` did not rerun.

**Comment by davidhewitt** [comment]
Ah, that's an interesting edge case. I think it's probably too complex to fix in PyO3 due to cargo limitations, we should remember this if users come with similar issues.
