### ISSUE TITLE
`maturin pep517 write-dist-info` fails with `OSError` on osx-arm64 conda-forge runner

### ISSUE THREAD

**Issue by mlondschien** [PyO3/maturin#1245]
### Bug Description

Conda-forge upgraded the OSX image of their virtual machines from 10.15 to 11. Now, when running `maturin pep517 write-dist-info` on their machines compiling for osx-arm64, this raises an
```
OSError: [Errno 86] Bad CPU type in executable: 'maturin'
```

Note that to my best understanding conda-forge cross-compiles for osx-arm64.

Longer stacktrace:
```
  Running `maturin pep517 write-dist-info --metadata-directory /private/tmp/pip-modern-metadata-pq609hbz --interpreter /Users/runner/miniforge3/conda-bld/changeforest_1667354960722/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python`
  Traceback (most recent call last):
    File "/Users/runner/miniforge3/conda-bld/changeforest_1667354960722/_build_env/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
      main()
    File "/Users/runner/miniforge3/conda-bld/changeforest_1667354960722/_build_env/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/runner/miniforge3/conda-bld/changeforest_1667354960722/_build_env/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/Users/runner/miniforge3/conda-bld/changeforest_1667354960722/_build_env/venv/lib/python3.10/site-packages/maturin/__init__.py", line 174, in prepare_metadata_for_build_wheel
      output = subprocess.check_output(command)
    File "/Users/runner/miniforge3/conda-bld/changeforest_1667354960722/_build_env/lib/python3.10/subprocess.py", line 420, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/Users/runner/miniforge3/conda-bld/changeforest_1667354960722/_build_env/lib/python3.10/subprocess.py", line 501, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/Users/runner/miniforge3/conda-bld/changeforest_1667354960722/_build_env/lib/python3.10/subprocess.py", line 969, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/Users/runner/miniforge3/conda-bld/changeforest_1667354960722/_build_env/lib/python3.10/subprocess.py", line 1845, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  OSError: [Errno 86] Bad CPU type in executable: 'maturin'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
```

[Pipeline](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=603099&view=logs&j=c35410bf-a820-56fd-e231-d3cd4bead63c&t=b92b255f-9dfe-5c14-4730-460f7a671001)

[PR 1](https://github.com/conda-forge/changeforest-feedstock/pull/22), [PR 2](https://github.com/conda-forge/biosphere-feedstock/pull/7).

[This](https://github.com/matplotlib/matplotlib/issues/15399/#issuecomment-540815965) might be related.

Locally (Mac osx-arm64 with osx 11) `maturin pep517 write-dist-info --metadata-directory . --interpreter python` runs through.

### Your Python version (`python -V`)

3.10

### Your pip version (`pip -V`)

-

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

See above.

**Comment by messense** [comment]
This should be report to https://github.com/conda-forge/maturin-feedstock instead.

**Comment by messense** [comment]
<img width="838" alt="image" src="https://user-images.githubusercontent.com/1556054/199657218-e190547e-befd-41fe-8cb7-25e90bb6a0e4.png">

From the log, conda installs `0.13.6-py310h1dc5ec9_1` which is arm64 only, so I think it's the issue with conda since when cross compiling it should install a x86_64 version.

**Comment by xhochy** [comment]
@mlondschien You probably need `maturin` also in the `build` section of your `requirements` to fix this problem.
