### ISSUE TITLE
`<package>.libs: cannot read file data: Is a directory` when building package with release flag

### ISSUE THREAD

**Issue by haixuanTao** [PyO3/maturin#1321]
### Bug Description

Building a package with the release flag makes an import error in python as follows:
```python
>>> import dora
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/peter/miniconda3/envs/dora3.8/lib/python3.8/site-packages/dora/__init__.py", line 1, in <module>
    from .dora import *
ImportError: /home/peter/miniconda3/envs/dora3.8/lib/python3.8/site-packages/dora/../dora.libs: cannot read file data: Is a directory
```

This does not happen on `maturin build` or `develop`, only on `maturin publish` and `maturin build --release` It's probably linked to an optimisation step of the library.

### Your maturin version (`maturin --version`)

0.14

### Your Python version (`python -V`)

Python 3.8.13

### Your pip version (`pip -V`)

pip 22.3.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

To recreate the error you can try to build dora:
```bash
git clone https://github.com/dora-rs/dora
cd apis/python/node
maturin build --release
```
or install `dora-rs` via pip, the release pipeline before that is the following: https://github.com/dora-rs/dora/actions/runs/3596328523/jobs/6056870777
```
pip install dora-rs==0.1.1
python -c "import dora"
```

**Comment by messense** [comment]
* Does this only happen with conda?
* Does `maturin build --compatibility off` then run [auditwheel](https://github.com/pypa/auditwheel) on wheels produces usable wheels?

**Comment by messense** [comment]
```bash
pip install dora-rs==0.1.1
python -c "import dora"
```

I'm unable to reproduce it in Python venv (3.11) and conda venv (3.8 and 3.10) on Ubuntu x86_64.

**Comment by haixuanTao** [comment]
> Does maturin build --release --compatibility off then run [auditwheel](https://github.com/pypa/auditwheel) on wheels produces usable wheels?

Running `maturin build --release --compatibility off` make the wheel usable without using auditwheel. I'm having issues with `auditwheel` installed via pip.

```bash
auditwheel: error: cannot repair "/home/peter/Documents/CONTRIB/dora/target/wheels/dora_rs-0.1.1-cp37-abi3-linux_x86_64.whl" to "manylinux_2_5_x86_64" ABI because of the presence of too-recent versioned symbols. You'll need to compile the wheel on an older toolchain.
```

I'm using Ubuntu 20.04 x86_64, that might be it.

You can do the following to reproduce:
```bash
docker run -it  continuumio/anaconda3:latest
pip install dora-rs
python -c "import dora"
```

Which gives me the following:
```
(base) root@972082ab61cc:/# pip install dora-rs
Collecting dora-rs
  Downloading dora_rs-0.1.1-cp37-abi3-manylinux_2_31_x86_64.whl (7.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 11.9 MB/s eta 0:00:00
Installing collected packages: dora-rs
Successfully installed dora-rs-0.1.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
(base) root@972082ab61cc:/# python -c "import dora"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.9/site-packages/dora/__init__.py", line 1, in <module>
    from .dora import *
ImportError: /opt/conda/lib/python3.9/site-packages/dora/../dora.libs: cannot read file data: Is a directory
```

**Comment by messense** [comment]
> ```shell
> auditwheel: error: cannot repair "/home/peter/Documents/CONTRIB/dora/target/wheels/dora_rs-0.1.1-cp37-abi3-linux_x86_64.whl" to "manylinux_2_5_x86_64" ABI because of the presence of too-recent versioned symbols. You'll need to compile the wheel on an older toolchain.
> ```

You need to pass `--plat manylinux_2_31` to auditwheel.

**Comment by messense** [comment]
Looks like the `DT_NEEDED` section is wrong after `patchelf`

```
root@e323eb165a8a:~# readelf -d /usr/local/lib/python3.8/dist-packages/dora/dora.abi3.so

Dynamic section at offset 0xd1d000 contains 37 entries:
  Tag        Type                         Name/Value
 0x000000000000000f (RPATH)              Library rpath: [$ORIGIN/../dora.libs]
 0x0000000000000001 (NEEDED)             Shared library: [libssl-578d2f9a.so.1.1]
 0x0000000000000001 (NEEDED)             Shared library: [libcrypto-d578cd7f.so.1.1]
 0x0000000000000001 (NEEDED)             Shared library: [$ORIGIN/../dora.libs]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000000c (INIT)               0xc1000
 0x000000000000000d (FINI)               0x966324
 0x0000000000000019 (INIT_ARRAY)         0xca08e0
 0x000000000000001b (INIT_ARRAYSZ)       888 (bytes)
 0x000000000000001a (FINI_ARRAY)         0xca0c58
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0xdb3d80
 0x0000000000000005 (STRTAB)             0xdb4290
 0x0000000000000006 (SYMTAB)             0xdb6028
 0x000000000000000a (STRSZ)              7570 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0xd10170
 0x0000000000000002 (PLTRELSZ)           2592 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0xc01a0
 0x0000000000000007 (RELA)               0x49b8
 0x0000000000000008 (RELASZ)             767976 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x000000006ffffffe (VERNEED)            0x46a8
 0x000000006fffffff (VERNEEDNUM)         10
 0x000000006ffffff0 (VERSYM)             0x43ac
 0x000000006ffffff9 (RELACOUNT)          31660
 0x0000000000000000 (NULL)               0x0
```

`0x0000000000000001 (NEEDED)             Shared library: [$ORIGIN/../dora.libs]` this shouldn't happen, since Ubuntu 22.04 works, my guess is that you build the Ubuntu 20.04 with a old version of `patchelf` that might have some bugs, we have encountered similar issue in the past: https://github.com/PyO3/maturin/issues/1165#issuecomment-1269992882

**Comment by haixuanTao** [comment]
Indeed. So using `patchelf` 0.17 fixed the issue.

Thanks @messense for the quick response. :1st_place_medal:
