### ISSUE TITLE
Incorrect platform tag with external dependencies

### ISSUE THREAD

**Issue by jneem** [PyO3/maturin#1490]
### Bug Description

I'm creating a python extension module with external library dependencies (specifically, `ffmpeg`). When I build the library with `maturin` on certain systems, it tags the resulting package as `manylinux_2_28` even though some of the bundled library dependencies have `GLIBC_2.29` symbols.

`auditwheel` correctly identifies the built package as requiring `manylinux_2_31`.

### Your maturin version (`maturin --version`)

0.14.3

### Your Python version (`python -V`)

Python 3.7.15

### Your pip version (`pip -V`)

pip 23.0

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. Check out the repository [here](https://github.com/jneem/maturin-manylinux)
2. Run `docker build .`

This builds a package in a `python:3.7.15-slim-bullseye` container and then tries to install it in a `python:3.3.3-slim-buster` container. The package installs without error, but trying to import the module results in
```
Traceback (most recent call last):
  File "example.py", line 1, in <module>
    import bug_report
  File "/usr/local/lib/python3.7/site-packages/bug_report/__init__.py", line 1, in <module>
    from .bug_report import *
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/python3.7/site-packages/bug_report/../bug_report.libs/libavcodec-a571829e.so.58)
```

**Comment by messense** [comment]
Thanks for reporting, definitely an oversight that should be fixed.

**Comment by cocool97** [comment]
Having the same issue using v1.8.2, building for manylinux_2_25 still requires GLIBC 2.39 (GLIBC version when building) at runtime.

Any updates on a fix ?

**Comment by messense** [comment]
No updates yet, the fix will only make it identify that the wheel requires GLIBC 2.39 for you, it won't magically make it compatible with manylinux_2_25 though. 
Thus this is a low priority issue ATM, and auditwheel can be used instead as a workaround.
