### ISSUE TITLE
UniFFI undefined symbol with out-of-the-box example

### ISSUE THREAD

**Issue by mario4tier** [PyO3/maturin#1574]
### Bug Description

Generated C symbols in .py not matching the ones in elf. Was able to reproduce the same using minimal demo from Maturin.

In short, 'maturin new --bindings uniffi testfoo' followed by 'maturin develop'. At python console getting:

```
>>> import testfoo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jdoe/rust/env/lib/python3.10/site-packages/testfoo/__init__.py", line 1, in <module>
    from .example import *  # NOQA
  File "/home/jdoe/rust/env/lib/python3.10/site-packages/testfoo/example.py", line 347, in <module>
    _UniFFILib.example_c1f8_add.argtypes = (
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/jdoe/rust/env/lib/python3.10/site-packages/testfoo/libuniffi_example.so: undefined symbol: example_c1f8_add
```

Elf shows:
```
$ readelf --syms -W /home/jdoe/rust/env/lib/python3.10/site-packages/testfoo/libuniffi_example.so | grep example
    52: 0000000000008e90    95 FUNC    GLOBAL DEFAULT   12 ffi_example_d92_rustbuffer_reserve
    53: 0000000000008ef0   268 FUNC    GLOBAL DEFAULT   12 example_d92_add
    54: 0000000000008da0    55 FUNC    GLOBAL DEFAULT   12 ffi_example_d92_rustbuffer_alloc
    56: 0000000000008e50    61 FUNC    GLOBAL DEFAULT   12 ffi_example_d92_rustbuffer_free
    57: 0000000000008de0    99 FUNC    GLOBAL DEFAULT   12 ffi_example_d92_rustbuffer_from_bytes
   353: 00000000000080b0    13 FUNC    LOCAL  DEFAULT   12 _ZN4core3ptr233drop_in_place$LT$uniffi..ffi..rustcalls..make_call$LT$uniffi..ffi..rustcalls..call_with_output$LT$testfoo..example_d92_add..$u7b$$u7b$closure$u7d$$u7d$$C$u32$GT$..$u7b$$u7b$closure$u7d$$u7d$$C$u32$GT$..$u7b$$u7b$closure$u7d$$u7d$$GT$17h8b838823d25fa11aE
   738: 0000000000007c60   679 FUNC    LOCAL  DEFAULT   12 _ZN7testfoo15example_d92_add28_$u7b$$u7b$closure$u7d$$u7d$17h286bc13d6981f722E
  1190: 0000000000008e90    95 FUNC    GLOBAL DEFAULT   12 ffi_example_d92_rustbuffer_reserve
  1213: 0000000000008e50    61 FUNC    GLOBAL DEFAULT   12 ffi_example_d92_rustbuffer_free
  1214: 0000000000008ef0   268 FUNC    GLOBAL DEFAULT   12 example_d92_add
  1227: 0000000000008de0    99 FUNC    GLOBAL DEFAULT   12 ffi_example_d92_rustbuffer_from_bytes
  1229: 0000000000008da0    55 FUNC    GLOBAL DEFAULT   12 ffi_example_d92_rustbuffer_alloc
```

.py shows:
```
$ cat /home/jdoe/rust/env/lib/python3.10/site-packages/testfoo/example.py | grep example
        return rust_call(_UniFFILib.ffi_example_c1f8_rustbuffer_alloc, size)
        return rust_call(_UniFFILib.ffi_example_c1f8_rustbuffer_reserve, rbuf, additional)
        return rust_call(_UniFFILib.ffi_example_c1f8_rustbuffer_free, self)
    lib = libname.format("uniffi_example")
_UniFFILib.example_c1f8_add.argtypes = (
_UniFFILib.example_c1f8_add.restype = ctypes.c_uint32
_UniFFILib.ffi_example_c1f8_rustbuffer_alloc.argtypes = (
_UniFFILib.ffi_example_c1f8_rustbuffer_alloc.restype = RustBuffer
_UniFFILib.ffi_example_c1f8_rustbuffer_from_bytes.argtypes = (
_UniFFILib.ffi_example_c1f8_rustbuffer_from_bytes.restype = RustBuffer
_UniFFILib.ffi_example_c1f8_rustbuffer_free.argtypes = (
_UniFFILib.ffi_example_c1f8_rustbuffer_free.restype = None
_UniFFILib.ffi_example_c1f8_rustbuffer_reserve.argtypes = (
_UniFFILib.ffi_example_c1f8_rustbuffer_reserve.restype = RustBuffer
    return FfiConverterUInt32.lift(rust_call(_UniFFILib.example_c1f8_add,
```

I am a first time Maturin + UniFFI user.

On the exact same setup, it works with changing only to "--binding pyo3"

### Your maturin version (`maturin --version`)

maturin 0.14.17

### Your Python version (`python -V`)

Python 3.10.6

### Your pip version (`pip -V`)

pip 23.1

### What bindings you're using

uniffi

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

```
$ cd /home/jdoe/rust
$ RUST_LOG=maturin=debug maturin new --bindings uniffi testfoo
  ✨ Done! New project created testfoo
$ cd testfoo
$ pip list
Package        Version
-------------- -------
maturin        0.14.17
pip            23.1
tomli          2.0.1
uniffi_bindgen 0.21.0
$ rustc --version
rustc 1.68.2 (9eb3afe9e 2023-03-27)
$ RUST_LOG=maturin=debug maturin develop
2023-04-21T01:14:14.079664Z DEBUG maturin::project_layout: Found pyproject.toml in working directory at "/home/jdoe/rust/testfoo/pyproject.toml"
2023-04-21T01:14:14.080331Z DEBUG maturin::project_layout: Using cargo manifest path from working directory: "/home/jdoe/rust/testfoo/Cargo.toml"
2023-04-21T01:14:14.080571Z DEBUG maturin::project_layout: Resolving cargo metadata from "/home/jdoe/rust/testfoo/Cargo.toml"
    Updating crates.io index
2023-04-21T01:14:15.029324Z DEBUG maturin::project_layout: Project layout resolved project_root=/home/jdoe/rust/testfoo python_dir=/home/jdoe/rust/testfoo rust_module=/home/jdoe/rust/testfoo/testfoo python_module=/home/jdoe/rust/testfoo/testfoo extension_name=testfoo
🔗 Found uniffi bindings
2023-04-21T01:14:15.138655Z DEBUG maturin::python_interpreter: Found CPython interpreter at /home/jdoe/rust/env/bin/python
2023-04-21T01:14:15.138785Z DEBUG maturin::compile: Running "cargo" "rustc" "--manifest-path" "/home/jdoe/rust/testfoo/Cargo.toml" "--message-format" "json" "--lib"
   Compiling proc-macro2 v1.0.56
   Compiling unicode-ident v1.0.8
   Compiling quote v1.0.26
   Compiling version_check v0.9.4
   Compiling serde_derive v1.0.160
   Compiling serde v1.0.160
   Compiling syn v1.0.109
   Compiling memchr v2.5.0
   Compiling minimal-lexical v0.2.1
   Compiling mime v0.3.17
   Compiling autocfg v1.1.0
   Compiling libc v0.2.142
   Compiling askama_escape v0.10.3
   Compiling log v0.4.17
   Compiling itoa v1.0.6
   Compiling ryu v1.0.13
   Compiling hashbrown v0.12.3
   Compiling cfg-if v1.0.0
   Compiling os_str_bytes v6.5.0
   Compiling heck v0.4.1
   Compiling camino v1.1.4
   Compiling anyhow v1.0.70
   Compiling paste v1.0.12
   Compiling serde_json v1.0.96
   Compiling textwrap v0.16.0
   Compiling plain v0.2.3
   Compiling termcolor v1.2.0
   Compiling once_cell v1.17.1
   Compiling siphasher v0.3.10
   Compiling strsim v0.10.0
   Compiling bitflags v1.3.2
   Compiling fs-err v2.9.0
   Compiling semver v1.0.17
   Compiling bytes v1.4.0
   Compiling static_assertions v1.1.0
   Compiling clap_lex v0.2.4
   Compiling unicase v2.6.0
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling indexmap v1.9.3
   Compiling nom v7.1.3
   Compiling syn v2.0.15
   Compiling mime_guess v2.0.4
   Compiling atty v0.2.14
   Compiling weedle2 v4.0.0
   Compiling scroll_derive v0.11.0
   Compiling clap_derive v3.2.18
   Compiling uniffi_checksum_derive v0.21.1
   Compiling scroll v0.11.0
   Compiling goblin v0.5.4
   Compiling clap v3.2.23
   Compiling toml v0.5.11
   Compiling uniffi_meta v0.21.1
   Compiling bincode v1.3.3
   Compiling cargo-platform v0.1.2
   Compiling cargo_metadata v0.14.2
   Compiling askama_shared v0.12.2
   Compiling askama_derive v0.11.2
   Compiling askama v0.11.1
   Compiling uniffi_bindgen v0.21.1
   Compiling uniffi_build v0.21.1
   Compiling uniffi_macros v0.21.1
   Compiling testfoo v0.1.0 (/home/jdoe/rust/testfoo)
   Compiling uniffi v0.21.1
    Finished dev [unoptimized + debuginfo] target(s) in 47.22s
2023-04-21T01:15:02.434630Z DEBUG maturin::module_writer: Adding testfoo-0.1.0.dist-info/METADATA
2023-04-21T01:15:02.435062Z DEBUG maturin::module_writer: Adding testfoo-0.1.0.dist-info/WHEEL
2023-04-21T01:15:02.436398Z DEBUG maturin::module_writer: Adding testfoo/__init__.py
2023-04-21T01:15:02.436723Z DEBUG maturin::module_writer: Adding testfoo/example.py from /home/jdoe/rust/testfoo/target/maturin/uniffi/example.py
2023-04-21T01:15:02.437462Z DEBUG maturin::module_writer: Adding testfoo/libuniffi_example.so from /home/jdoe/rust/testfoo/target/debug/libtestfoo.so
2023-04-21T01:15:03.021286Z DEBUG maturin::module_writer: Adding testfoo-0.1.0.dist-info/RECORD
📦 Built wheel to /tmp/.tmpkCv1jh/testfoo-0.1.0-py3-none-linux_x86_64.whl
🛠 Installed testfoo-0.1.0
$ pip show testfoo
Name: testfoo
Version: 0.1.0
Summary:
Home-page:
Author:
Author-email:
License:
Location: /home/jdoe/rust/env/lib/python3.10/site-packages
Requires:
Required-by:
$ python
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import testfoo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jdoe/rust/env/lib/python3.10/site-packages/testfoo/__init__.py", line 1, in <module>
    from .example import *  # NOQA
  File "/home/jdoe/rust/env/lib/python3.10/site-packages/testfoo/example.py", line 347, in <module>
    _UniFFILib.example_c1f8_add.argtypes = (
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/jdoe/rust/env/lib/python3.10/site-packages/testfoo/libuniffi_example.so: undefined symbol: example_c1f8_add
>>>
```

**Comment by messense** [comment]
maturin 0.14.x only supports UniFFI 0.21.x and it's not actively tested on CI. Can you try maturin prerelease: `pip install -U --pre maturin`, it supports newer UniFFI version.

**Comment by mario4tier** [comment]
Thank you for the quick response.

Latest maturin-1.0.0b7 (with UniFFI 0.23.0) works.

I am now all set. Thanks again.
