### ISSUE TITLE
pep517 backend attempts to shlex.split config_settings 

### ISSUE THREAD

**Issue by ionenwks** [PyO3/maturin#1623]
### Bug Description

https://github.com/PyO3/maturin/blob/5dc4d7a4c8abeb275c6762e2d6a0c4ae4ab169b2/maturin/__init__.py#L47

Not super familiar with this but `return shlex.split(args)` I get:
```
>>> Compiling source in /tmp/portage/dev-python/adblock-0.6.0/work/python-adblock-0.6.0 ...
 * python3_11: running distutils-r1_run_phase distutils-r1_python_compile
 *   Building the wheel for python-adblock-0.6.0 via maturin
gpep517 build-wheel --backend maturin --output-fd 3 --wheel-dir /tmp/portage/dev-python/adblock-0.6.0/work/python-adblock-0.6.0-python3_11/wheel --config-json {"build-args": ["--jobs=11", "--skip-auditwheel"]}
2023-05-20 12:01:13,877 gpep517 INFO Building wheel via backend maturin
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/gpep517", line 4, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/gpep517/__main__.py", line 406, in main
    return func(args)
           ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gpep517/__main__.py", line 202, in build_wheel
    print(build_wheel_impl(args, args.wheel_dir), file=out)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gpep517/__main__.py", line 194, in build_wheel_impl
    wheel_name = backend.build_wheel(str(wheel_dir), args.config_json)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/maturin/__init__.py", line 108, in build_wheel
    return _build_wheel(wheel_directory, config_settings, metadata_directory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/maturin/__init__.py", line 81, in _build_wheel
    pep517_args = get_maturin_pep517_args(config_settings)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/maturin/__init__.py", line 47, in get_maturin_pep517_args
    return shlex.split(args)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/shlex.py", line 315, in split
    return list(lex)
           ^^^^^^^^^
  File "/usr/lib/python3.11/shlex.py", line 300, in __next__
    token = self.get_token()
            ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/shlex.py", line 109, in get_token
    raw = self.read_token()
          ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/shlex.py", line 140, in read_token
    nextchar = self.instream.read(1)
               ^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'read'
```

But with `return args` it's fine:
```
>>> Compiling source in /tmp/portage/dev-python/adblock-0.6.0/work/python-adblock-0.6.0 ...
 * python3_11: running distutils-r1_run_phase distutils-r1_python_compile
 *   Building the wheel for python-adblock-0.6.0 via maturin
gpep517 build-wheel --backend maturin --output-fd 3 --wheel-dir /tmp/portage/dev-python/adblock-0.6.0/work/python-ad
block-0.6.0-python3_11/wheel --config-json {"build-args": ["--jobs=11", "--skip-auditwheel"]}
2023-05-20 11:58:14,963 gpep517 INFO Building wheel via backend maturin
Running `maturin pep517 build-wheel -i /usr/bin/python3.11 --compatibility off --jobs=11 --skip-auditwheel`
```

Issue aside, thanks for adding this. It integrates with better than the env var for us.

### Your maturin version (`maturin --version`)

0.15.3

### Your Python version (`python -V`)

Python 3.11.3

### Your pip version (`pip -V`)

pip 23.1.2

### What bindings you're using

None

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [x] Yes

### Steps to Reproduce

N/A

**Comment by ionenwks** [comment]
Or well, at first I set it up like we do for meson-python and setuptools, but I guess it works if I pass it as a single string rather than already split.

**Comment by ionenwks** [comment]
Works for me either way, just would like to know if it's going to stay like that or not before make changes on which method to use.

**Comment by messense** [comment]
Well, I think we can should both.
