### ISSUE TITLE
msys2: whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by benruijl** [PyO3/maturin#2217]
### Bug Description

I am trying to create a Windows Python wheel for my crate [Symbolica](https://github.com/benruijl/symbolica/tree/windows). Since it depends on `gmp`, I have to use msys2 to compile it (see https://github.com/stegos/gmp-mpfr-sys?tab=readme-ov-file#building-on-windows).

I get:
```
$ maturin develop
🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.7
🐍 Using CPython 3.11 at C:/msys64/home/benru/symbolica/.env/bin/python.exe to generate to link bindings (With abi3, an interpreter is only required on windows)
📡 Using build options features from pyproject.toml
   Compiling symbolica v0.10.0 (C:\msys64\home\benru\symbolica)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 6.25s
📖 Found type stub file at symbolica.pyi
📦 Built wheel for abi3 Python ≥ 3.7 to C:\msys64\tmp\.tmpDIFxD4\symbolica-0.10.0-cp37-abi3-win_amd64.whl
💥 maturin failed
  Caused by: pip install in C:/msys64/home/benru/symbolica/.env failed running ["-m", "pip", "--disable-pip-version-check", "install", "--no-deps", "--force-reinstall", "C:\\msys64\\tmp\\.tmpDIFxD4\\symbolica-0.10.0-cp37-abi3-win_amd64.whl"]: exit code: 1
--- Stdout:

--- Stderr:
ERROR: symbolica-0.10.0-cp37-abi3-win_amd64.whl is not a supported wheel on this platform.
---
``` 

### Your maturin version (`maturin --version`)

1.7.1

### Your Python version (`python -V`)

3.11.10

### Your pip version (`pip -V`)

24.0

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

In MSYS2 I install:
- m4
- git
- mingw-w64-x86_64-gcc
- [mingw-w64-x86_64-rust](https://packages.msys2.org/package/mingw-w64-x86_64-rust?repo=mingw64)
- [mingw-w64-python-maturin](https://packages.msys2.org/base/mingw-w64-python-maturin)
- mingw-w64-x86_64-python
- mingw-w64-x86_64-python-pip

and do 

```
git clone https://github.com/benruijl/symbolica.git
cd symbolica
git checkout windows
```
and run
```
python -m venv .env
maturin develop
```

I get:
```
$ maturin develop
🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.7
🐍 Using CPython 3.11 at C:/msys64/home/benru/symbolica/.env/bin/python.exe to generate to link bindings (With abi3, an interpreter is only required on windows)
📡 Using build options features from pyproject.toml
   Compiling symbolica v0.10.0 (C:\msys64\home\benru\symbolica)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 6.25s
📖 Found type stub file at symbolica.pyi
📦 Built wheel for abi3 Python ≥ 3.7 to C:\msys64\tmp\.tmpDIFxD4\symbolica-0.10.0-cp37-abi3-win_amd64.whl
💥 maturin failed
  Caused by: pip install in C:/msys64/home/benru/symbolica/.env failed running ["-m", "pip", "--disable-pip-version-check", "install", "--no-deps", "--force-reinstall", "C:\\msys64\\tmp\\.tmpDIFxD4\\symbolica-0.10.0-cp37-abi3-win_amd64.whl"]: exit code: 1
--- Stdout:

--- Stderr:
ERROR: symbolica-0.10.0-cp37-abi3-win_amd64.whl is not a supported wheel on this platform.
---
```

**Comment by messense** [comment]
What's the output of `python -m pip debug --verbose` using the python installed in msys2?

**Comment by benruijl** [comment]
The output is:
```
benru@DESKTOP MINGW64 ~/symbolica
$ python -m pip debug --verbose
WARNING: This command is only meant for debugging. Do not use this with automation for parsing and getting these details, since the output and options of this command may change without notice.
pip version: pip 24.0 from C:/msys64/home/benru/symbolica/.env/lib/python3.11/site-packages/pip (python 3.11)
sys.version: 3.11.10 (main, Sep 10 2024, 13:02:13)  [GCC 14.2.0 64 bit (AMD64)]
sys.executable: C:/msys64/home/benru/symbolica/.env/bin/python.exe
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: cp1252
sys.platform: win32
sys.implementation:
  name: cpython
'cert' config value: Not specified
REQUESTS_CA_BUNDLE: None
CURL_CA_BUNDLE: None
pip._vendor.certifi.where(): C:/msys64/home/benru/symbolica/.env/lib/python3.11/site-packages/pip/_vendor/certifi/cacert.pem
pip._vendor.DEBUNDLED: False
vendored library versions:
  CacheControl==0.13.1
  colorama==0.4.6
  distlib==0.3.8
  distro==1.8.0
  msgpack==1.0.5
  packaging==21.3
  platformdirs==3.8.1
  pyparsing==3.1.0
  pyproject-hooks==1.0.0
  requests==2.31.0
  certifi==2023.07.22
  chardet==5.1.0
  idna==3.4
  urllib3==1.26.17
  rich==13.4.2 (Unable to locate actual module version, using vendor.txt specified version)
  pygments==2.15.1
  typing_extensions==4.7.1 (Unable to locate actual module version, using vendor.txt specified version)
  resolvelib==1.0.1
  setuptools==68.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  six==1.16.0
  tenacity==8.2.2 (Unable to locate actual module version, using vendor.txt specified version)
  tomli==2.0.1
  truststore==0.8.0
  webencodings==0.5.1 (Unable to locate actual module version, using vendor.txt specified version)
Compatible tags: 39
  cp311-cp311-mingw_x86_64
  cp311-abi3-mingw_x86_64
  cp311-none-mingw_x86_64
  cp310-abi3-mingw_x86_64
  cp39-abi3-mingw_x86_64
  cp38-abi3-mingw_x86_64
  cp37-abi3-mingw_x86_64
  cp36-abi3-mingw_x86_64
  cp35-abi3-mingw_x86_64
  cp34-abi3-mingw_x86_64
  cp33-abi3-mingw_x86_64
  cp32-abi3-mingw_x86_64
  py311-none-mingw_x86_64
  py3-none-mingw_x86_64
  py310-none-mingw_x86_64
  py39-none-mingw_x86_64
  py38-none-mingw_x86_64
  py37-none-mingw_x86_64
  py36-none-mingw_x86_64
  py35-none-mingw_x86_64
  py34-none-mingw_x86_64
  py33-none-mingw_x86_64
  py32-none-mingw_x86_64
  py31-none-mingw_x86_64
  py30-none-mingw_x86_64
  cp311-none-any
  py311-none-any
  py3-none-any
  py310-none-any
  py39-none-any
  py38-none-any
  py37-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any
```

**Comment by benruijl** [comment]
I also tried loading this wheel outside of msys2, on the 'pure' Windows Python installation (which is actually the intended target). There I get `pip` to install it, but it doesn't import:

```
Python 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
KeyboardInterrupt
>>> import symbolica
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\benru\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\symbolica\__init__.py", line 1, in <module>
    from .symbolica import *
ImportError: DLL load failed while importing symbolica: The specified module could not be found.
>>>
```

**Comment by messense** [comment]
> ERROR: symbolica-0.10.0-cp37-abi3-win_amd64.whl is not a supported wheel on this platform.

This error is because `win_amd64` isn't a compatible tags (look at the `Compatible tags: 39` list) in this msys2 python.

I'm not sure about the `ImportError`, probably due to ABI mismatch?

**Comment by messense** [comment]
Personally I have no real experence using msys2 so I won't be able to help much, consider raise an issue in https://github.com/msys2/MINGW-packages/issues?q=is%3Aissue+is%3Aopen+python-maturin or https://github.com/msys2-contrib/cpython-mingw/issues instead.

**Comment by benruijl** [comment]
Do you think that if I use the same Python version in vanilla Windows as I used in msys2 for the compilation (3.11.10), the library will load, even though the interpreter running on a different target?

Can I extract any useful information from the `pyd`? Many thanks!

**Comment by benruijl** [comment]
This is interesting, it does find the init function:

![image](https://github.com/user-attachments/assets/aeb6c652-ecc9-415b-85c2-945cf6f703bb)


But it potentially can't find any of the referenced DLLs?

**Comment by benruijl** [comment]
The `delvewheel` program says:

```
Analyzing symbolica-0.10.0-cp37-abi3-win_amd64.whl

The following DLLs will be copied into the wheel.
    libpython3.dll (Error: Not Found)

The following DLLs are assumed to be present in the end user's environment and will not be copied into the wheel.
    advapi32.dll
    api-ms-win-core-synch-l1-2-0.dll
    bcrypt.dll
    bcryptprimitives.dll
    kernel32.dll
    msvcrt.dll
    ntdll.dll
    userenv.dll
    ws2_32.dll

Warning: At least one dependent DLL needs to be copied into the wheel but was not found.
```

Does this problem look familiar to you?

**Comment by benruijl** [comment]
Copying `python3.dll` to `libpython3.dll` and calling

```
delvewheel.exe repair C:\msys64\home\benru\symbolica\target\wheels\symbolica-0.10.0-cp37-abi3-win_amd64.whl --add-path .
```

created a new wheel that does successfully get imported! The question now is: where in the toolchain should this be fixed?

**Comment by benruijl** [comment]
Simply copying `python3.dll` to `libpython3.dll` in the Windows Python installation folder also allows for the original wheel to get imported.

@messense shouldn't `maturin` in link to `python3.dll` for the platform `abi3-win_amd64`?

**Comment by benruijl** [comment]
Thanks! The following command removes the linker issue but silently crashes the Python interpreter when doing `import symbolica`:

```
PYO3_CROSS_LIB_DIR="C:/Users/benru/AppData/Local/Programs/Python/Python311" maturin build
```

Do you have any suggestions?
