### ISSUE TITLE
Couldn't find any python interpreters

### ISSUE THREAD

**Issue by dwpeng** [PyO3/maturin#2293]
### Bug Description

```bash
  Downloaded anstyle v1.0.8
  Downloaded android-tzdata v0.1.1
  Downloaded ahash v0.8.11
  Downloaded ciborium-io v0.2.2
  Downloaded addr2line v0.24.2
  Downloaded windows v0.57.0
📦 Including license file "/home/runner/work/filterx/filterx/LICENSE"
💥 maturin failed
  Caused by: Couldn't find any python interpreters. Please specify at least one with -i
Error: The process '/usr/bin/docker' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1702:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1685:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1579:27)
    at ChildProcess.emit (node:events:[519](https://github.com/dwpeng/filterx/actions/runs/11725617250/job/32662353547#step:3:526):28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
Error: The process '/usr/bin/docker' failed with exit code 1
```

full action log: https://github.com/dwpeng/filterx/actions/runs/11725617250/job/32662353547

### Your maturin version (`maturin --version`)

latest

### Your Python version (`python -V`)

.

### Your pip version (`pip -V`)

.

### What bindings you're using

bin

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

.

**Comment by kiefernforst** [comment]
@dwpeng What has been your solution?
