### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by tcirstea** [PyO3/maturin#232]
maturin is a dependency for orjson, which I'm hoping to use. However, there's no binary and it won't build. Here's an excerpt from `pip3 install maturin -vv`
```
Building wheels for collected packages: maturin
  Created temporary directory: /tmp/pip-wheel-xfduloq0
  Running setup.py bdist_wheel for maturin ...   Destination directory: /tmp/pip-wheel-xfduloq0
  Running command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-50kzifkp/maturin/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-xfduloq0 --python-tag cp37
  running bdist_wheel
  running build
  installing to build/bdist.linux-armv7l/wheel
  running install
  error: [Errno 2] No such file or directory: 'cargo': 'cargo'
error
  Failed building wheel for maturin
  Running setup.py clean for maturin
  Running command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-50kzifkp/maturin/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all
  running clean
  'build/lib' does not exist -- can't clean it
  'build/bdist.linux-armv7l' does not exist -- can't clean it
  'build/scripts-3.7' does not exist -- can't clean it
Failed to build maturin
Installing collected packages: maturin
  Created temporary directory: /tmp/pip-record-qkx984lk
  Running setup.py install for maturin ...     Running command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-50kzifkp/maturin/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-qkx984lk/install-record.txt --single-version-externally-managed --compile
    running install
    error: [Errno 2] No such file or directory: 'cargo': 'cargo'
error
Cleaning up...
  Removing source in /tmp/pip-install-50kzifkp/maturin
Removed build tracker '/tmp/pip-req-tracker-v18k8qvo'
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-50kzifkp/maturin/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-qkx984lk/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-50kzifkp/maturin/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 386, in run
    use_user_site=options.use_user_site,
  File "/usr/lib/python3/dist-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 791, in install
    spinner=spinner,
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 723, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-50kzifkp/maturin/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-qkx984lk/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-50kzifkp/maturin/
```
Python 3.7.3
uname -r: `4.19.75-v7l+`

**Comment by tcirstea** [comment]
It was naive to assume it would just work - I hadn't installed cargo/rust.
Now it fails on compiling `ring`

```
error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/src/lib.rs:69:1
     |
  69 | extern crate alloc;
     | ^^^^^^^^^^^^^^^^^^^
```

**Comment by tcirstea** [comment]
And of course the default version of rust doesn't work. The beta release using rustup fixed it.
I'll let the devs close this in case you want to add build instructions somewhere.

**Comment by tcirstea** [comment]
Maturin should fail to build on ARM with a correct error since using it will result in:
```
💥 maturin failed
Caused by: The architecture ARM is not supported
```

**Comment by konstin** [comment]
For the error in the initial error, I've written #236 which improves the error message for when rust isn't installed.

The second problem you described in https://github.com/PyO3/maturin/issues/232#issuecomment-552174445 is the rust version being to old: The alloc crate had been stabilized in rust 1.36.0 (s. https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1360-2019-07-04). That will be fixed by https://github.com/rust-lang/rfcs/pull/2495, likely by cargo saying that the rust version is too old.
