### ISSUE TITLE
Conda recipe for Maturin fails in macOS

### ISSUE THREAD

**Issue by apcamargo** [PyO3/maturin#268]
I'm trying to add Maturin to conda-forge (https://github.com/conda-forge/staged-recipes/pull/10902) but the recipe fails in macOS:

```
Packaging maturin
INFO conda_build.build:build(1571): Packaging maturin
Packaging maturin-0.7.7-py36h0b31af3_0
INFO conda_build.build:bundle_conda(891): Packaging maturin-0.7.7-py36h0b31af3_0
compiling .pyc files...
number of files: 8
Fixing linking of /System/Library/Frameworks/Security.framework/Versions/A/Security in /usr/local/miniconda/conda-bld/maturin_1582233876270/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/maturin
New link location is None
Fixing linking of /usr/lib/libSystem.B.dylib in /usr/local/miniconda/conda-bld/maturin_1582233876270/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/maturin
New link location is None
Fixing linking of /usr/lib/libresolv.9.dylib in /usr/local/miniconda/conda-bld/maturin_1582233876270/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/maturin
New link location is None

  ERROR (maturin,bin/maturin): /usr/lib/libresolv.9.dylib not found in sysroot, is this binary repackaging? .. do you need to use install_name_tool/patchelf?
   INFO (maturin,bin/maturin): Needed DSO /System/Library/Frameworks/Security.framework/Versions/A/Security found in the whitelist
   INFO (maturin,bin/maturin): Needed DSO /usr/lib/libSystem.B.dylib found in the whitelist
Traceback (most recent call last):
  File ".ci_support/build_all.py", line 135, in <module>
    build_all(args.recipes_dir, args.arch)
  File ".ci_support/build_all.py", line 68, in build_all
    build_folders(recipes_dir, new_comp_folders, arch, channel_urls)
  File ".ci_support/build_all.py", line 125, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 2344, in build_tree
    notest=notest,
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 1643, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 1002, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 867, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/post.py", line 1150, in post_build
    check_overlinking(m, files)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/post.py", line 1087, in check_overlinking
    m.config.enable_static)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/post.py", line 1051, in check_overlinking_impl
    raise OverLinkingError(overlinking_errors)
conda_build.exceptions.OverLinkingError: overlinking check failed 
['  ERROR (maturin,bin/maturin): /usr/lib/libresolv.9.dylib not found in sysroot, is this binary repackaging? .. do you need to use install_name_tool/patchelf?']
```
Does Maturin have an additional dependency in macOS?

**Comment by konstin** [comment]
Have you tried building with `--no-default-features`? The default features pull in some systems dependencies through the http stack. (I wouldn't recommend publishing binaries with  `--no-default-features` as then you can't use `maturin upload`, but it might help pinning down which dependency pulls in libresolv).

Otherwise I unfortunately can't help because I don't have a mac.

**Comment by apcamargo** [comment]
Currently I'm building the recipe using `setup.py`, to keep it as close as possible to other PyPI recipes. Is there any way of activating `--no-default-features` in this approach?

**Comment by konstin** [comment]
The setup.py installation unfortunately has no configuration options.

BTW in general I'd recommend to avoid the source distribution, since it's really just a fallback for platforms for which there are no binary wheels. maturin is self-hosting and releases (on pypi and on github) are made with `maturin publish`. For this it shouldn't matter too much however.

I don't know too much about conda, but it's possible to statically link maturin so that it passes even the manylinux1 constraints.

**Comment by apcamargo** [comment]
I don't think they allow pre-built releases. Everything must be build using their infrastructure. I think I'll have to figure out which libraries are missing.

Thanks!

**Comment by apcamargo** [comment]
Just as an update, I managed to fix the issue (with the help of the conda-forge guys) and maturin is now installable via Conda

**Comment by konstin** [comment]
Great to hear! I'll close this then
