### ISSUE TITLE
Compiling with Docker fails: warning: spurious network error (2 tries remaining): could not read directory '/usr/local/cargo/registry/index/github.com-1ecc6299db9ec823/.git//refs': Value too large for defined data type; class=Os (2) (deliver arm binary?)

### ISSUE THREAD

**Issue by bloodbare** [PyO3/maturin#294]
On a Dockerfile like:

```
FROM arm32v7/python:3.7
RUN pip install cffi

ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH \
    RUST_VERSION=nightly-2020-01-23

RUN set -eux; \
    dpkgArch="$(dpkg --print-architecture)"; \
    case "${dpkgArch##*-}" in \
        amd64) rustArch='x86_64-unknown-linux-gnu'; rustupSha256='ad1f8b5199b3b9e231472ed7aa08d2e5d1d539198a15c5b1e53c746aad81d27b' ;; \
        armhf) rustArch='armv7-unknown-linux-gnueabihf'; rustupSha256='6c6c3789dabf12171c7f500e06d21d8004b5318a5083df8b0b02c0e5ef1d017b' ;; \
        arm64) rustArch='aarch64-unknown-linux-gnu'; rustupSha256='26942c80234bac34b3c1352abbd9187d3e23b43dae3cf56a9f9c1ea8ee53076d' ;; \
        i386) rustArch='i686-unknown-linux-gnu'; rustupSha256='27ae12bc294a34e566579deba3e066245d09b8871dc021ef45fc715dced05297' ;; \
        *) echo >&2 "unsupported architecture: ${dpkgArch}"; exit 1 ;; \
    esac; \
    url="https://static.rust-lang.org/rustup/archive/1.21.1/${rustArch}/rustup-init"; \
    wget "$url"; \
    echo "${rustupSha256} *rustup-init" | sha256sum -c -; \
    chmod +x rustup-init; \
    ./rustup-init -y --no-modify-path --profile minimal --default-toolchain $RUST_VERSION; \
    rm rustup-init; \
    chmod -R a+w $RUSTUP_HOME $CARGO_HOME; \
    rustup --version; \
    cargo --version; \
    rustc --version;

RUN pip install maturin
```

with docker x: `docker buildx build --platform linux/arm/v7 -t base_arm:1.0.0 -f Base.Arm.Dockerfile .`

I get an output:
```
 Building wheels for collected packages: maturin
#15 141.2     Building wheel for maturin (PEP 517): started
#15 141.2     Building wheel for maturin (PEP 517): finished with status 'error'
#15 141.2     ERROR: Command errored out with exit status 1:
#15 141.2      command: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpnrioj4iu
#15 141.2          cwd: /tmp/pip-install-bwwc2mpk/maturin
#15 141.2     Complete output (45 lines):
#15 141.2     running bdist_wheel
#15 141.2     running build
#15 141.2     installing to build/bdist.linux-armv7l/wheel
#15 141.2     running install
#15 141.2         Updating crates.io index
#15 141.2     warning: spurious network error (2 tries remaining): could not read directory '/usr/local/cargo/registry/index/github.com-1ecc6299db9ec823/.git//refs': Value too large for defined data type; class=Os (2)
#15 141.2     warning: spurious network error (1 tries remaining): could not read directory '/usr/local/cargo/registry/index/github.com-1ecc6299db9ec823/.git//refs': Value too large for defined data type; class=Os (2)
#15 141.2     error: failed to fetch `https://github.com/rust-lang/crates.io-index`
#15 141.2
#15 141.2     Caused by:
#15 141.2       could not read directory '/usr/local/cargo/registry/index/github.com-1ecc6299db9ec823/.git//refs': Value too large for defined data type; class=Os (2)
#15 141.2     Traceback (most recent call last):
#15 141.2       File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
#15 141.2         main()
#15 141.2       File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
#15 141.2         json_out['return_val'] = hook(**hook_input['kwargs'])
#15 141.2       File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 182, in build_wheel
#15 141.2         metadata_directory)
#15 141.2       File "/tmp/pip-build-env-41r39mzk/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 209, in build_wheel
#15 141.2         wheel_directory, config_settings)
#15 141.2       File "/tmp/pip-build-env-41r39mzk/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 194, in _build_with_temp_dir
#15 141.2         self.run_setup()
#15 141.2       File "/tmp/pip-build-env-41r39mzk/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
#15 141.2         exec(compile(code, __file__, 'exec'), locals())
#15 141.2       File "setup.py", line 97, in <module>
#15 141.2         zip_safe=False,
#15 141.2       File "/tmp/pip-build-env-41r39mzk/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
#15 141.2         return distutils.core.setup(**attrs)
#15 141.2       File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
#15 141.2         dist.run_commands()
#15 141.2       File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
#15 141.2         self.run_command(cmd)
#15 141.2       File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
#15 141.2         cmd_obj.run()
#15 141.2       File "/tmp/pip-build-env-41r39mzk/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 228, in run
#15 141.2         self.run_command('install')
#15 141.2       File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
#15 141.2         self.distribution.run_command(command)
#15 141.2       File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
#15 141.2         cmd_obj.run()
#15 141.2       File "setup.py", line 58, in run
#15 141.2         ["cargo", "rustc", "--bin", "maturin", "--", "-C", "link-arg=-s"]
#15 141.2       File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
#15 141.2         raise CalledProcessError(retcode, cmd)
#15 141.2     subprocess.CalledProcessError: Command '['cargo', 'rustc', '--bin', 'maturin', '--', '-C', 'link-arg=-s']' returned non-zero exit status 101.
#15 141.2     ----------------------------------------
#15 141.2     ERROR: Failed building wheel for maturin
#15 141.2   Failed to build maturin
#15 141.2   ERROR: Could not build wheels for maturin which use PEP 517 and cannot be installed directly
#15 141.2   ----------------------------------------
#15 141.7 ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-enmzymek/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'maturin>=0.8,<0.9' Check the logs for full command output.```

Docker version: `Docker version 19.03.8, build afacb8b` on Mac OS X

**Comment by konstin** [comment]
This is some odd networking error when running cargo and not caused by maturin.

**Comment by omarandlorraine** [comment]
I have no idea *why*, but this can happen if you are in a 32-bit environment on a 64-bit system (for example, your computer is an amd64, but you're inside a chroot that's armv6, and the filesystem is shared between both architectures. It seems to affect ext4 and possibly xfs, and perhaps others). It seems to affect docker, like you're using, and Qemu as well. [There is more information about this problem here](https://github.com/uraimo/run-on-arch-action/issues/9).

It is possible you can work around this by mounting tmpfs over cargo's index, in your case `/usr/local/cargo/registry/index/`. This will be a filesystem that is not shared between a 64-bit system and a 32-bit system. This will cause cargo to rebuild its indexes and re-download your package's dependencies.
