### ISSUE TITLE
Error installing maturin on Python3.8-alpine3.10

### ISSUE THREAD

**Issue by NotoriousRebel** [PyO3/maturin#322]
Here is the traceback:

```Collecting orjson<4,>=3
  Downloading orjson-3.0.2.tar.gz (649 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ggq9yudr/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/s
imple -- 'maturin>=0.8.1,<0.9'
       cwd: None
  Complete output (59 lines):
  Collecting maturin<0.9,>=0.8.1
    Downloading maturin-0.8.1.tar.gz (78 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting toml~=0.10.0
    Using cached toml-0.10.1-py2.py3-none-any.whl (19 kB)
  Building wheels for collected packages: maturin
    Building wheel for maturin (PEP 517): started
    Building wheel for maturin (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpkibrod9d
         cwd: /tmp/pip-install-rsfbw1wc/maturin
    Complete output (36 lines):
    running bdist_wheel
    running build
    installing to build/bdist.linux-x86_64/wheel
    running install
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
        main()
      File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 181, in build_wheel
        return _build_backend().build_wheel(wheel_directory, config_settings,
      File "/tmp/pip-build-env-ese20a8u/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 208, in build_wheel
        return self._build_with_temp_dir(['bdist_wheel'], '.whl',
      File "/tmp/pip-build-env-ese20a8u/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 194, in _build_with_temp_dir
        self.run_setup()
      File "/tmp/pip-build-env-ese20a8u/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 81, in <module>
File "/tmp/pip-build-env-ese20a8u/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-ese20a8u/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 228, in run
        self.run_command('install')
      File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "setup.py", line 54, in run
        raise RuntimeError(
    RuntimeError: cargo not found in PATH. Please install rust (https://www.rust-lang.org/tools/install) and try again
    ----------------------------------------
    ERROR: Failed building wheel for maturin
  Failed to build maturin
  ERROR: Could not build wheels for maturin which use PEP 517 and cannot be installed directly
  WARNING: You are using pip version 20.0.2; however, version 20.1.1 is available.
  You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ggq9yudr/overlay --no-warn-script-location --no-binary :none: --only-
binary :none: -i https://pypi.org/simple -- 'maturin>=0.8.1,<0.9' Check the logs for full command output.
WARNING: You are using pip version 20.0.2; however, version 20.1.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
```

Here is what my Dockerfile looks like:

```
FROM tiangolo/uvicorn-gunicorn:python3.8-alpine3.10
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh
RUN apk add --no-cache python3-dev
RUN git clone https://github.com/NotoriousRebel/theHarvester
RUN pip install -r theHarvester/theHarvester/lib/app/requirements.txt

**Comment by konstin** [comment]
It's a bit hidden under all the noise from pip, but otherwise pretty clear:

> RuntimeError: cargo not found in PATH. Please install rust (https://www.rust-lang.org/tools/install) and try again 

For now I'd recommend using a glibc-based distribution since there are some issues with shared libraries + rust + musl, but it's possible with some fiddling (see https://github.com/ijl/orjson/issues/46).
