### ISSUE TITLE
Fails to build on FreeBSD 12.2

### ISSUE THREAD

**Issue by syleishere** [PyO3/maturin#519]
Python 3.9.4
pip 21.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
FreeBSD 12.2-RELEASE-p6 FreeBSD 12.2-RELEASE-p6 GENERIC  amd64

Just keeps erroring out in a loop trying to install orjson over and over again.

```
# pip3.9 install --upgrade fastapi[all]
Requirement already satisfied: fastapi[all] in /usr/local/lib/python3.9/site-packages (0.52.0)
Collecting fastapi[all]
  Using cached fastapi-0.63.0-py3-none-any.whl (50 kB)
Collecting starlette==0.13.6
  Using cached starlette-0.13.6-py3-none-any.whl (59 kB)
Requirement already satisfied: pydantic<2.0.0,>=1.0.0 in /usr/local/lib/python3.9/site-packages (from fastapi[all]) (1.8.1)
Collecting ujson<4.0.0,>=3.0.0
  Downloading ujson-3.2.0.tar.gz (7.1 MB)
     |████████████████████████████████| 7.1 MB 9.1 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: jinja2<3.0.0,>=2.11.2 in /usr/local/lib/python3.9/site-packages (from fastapi[all]) (2.11.3)
Requirement already satisfied: python-multipart<0.0.6,>=0.0.5 in /usr/local/lib/python3.9/site-packages (from fastapi[all]) (0.0.5)
Collecting orjson<4.0.0,>=3.2.1
  Using cached orjson-3.5.2.tar.gz (740 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-_cqsq37c/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- maturin==0.10.3
       cwd: None
  Complete output (255 lines):
  Collecting maturin==0.10.3
    Using cached maturin-0.10.3.tar.gz (101 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting toml~=0.10.0
    Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
  Building wheels for collected packages: maturin
    Building wheel for maturin (PEP 517): started
    Building wheel for maturin (PEP 517): still running...
    Building wheel for maturin (PEP 517): still running...
    Building wheel for maturin (PEP 517): still running...
    Building wheel for maturin (PEP 517): still running...
    Building wheel for maturin (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpmmo2scpe
         cwd: /tmp/pip-install-aejl9q1c/maturin_87a7ed76948c462d81a3090eb63e4442
    Complete output (230 lines):
    running bdist_wheel
    running build
    installing to build/bdist.freebsd-12.2-RELEASE-p6-amd64/wheel
    running install
       Compiling libc v0.2.93
       Compiling proc-macro2 v1.0.26
       Compiling unicode-xid v0.2.1
       Compiling syn v1.0.69
       Compiling cfg-if v1.0.0
       Compiling autocfg v1.0.1
       Compiling version_check v0.9.3
       Compiling serde_derive v1.0.125
       Compiling memchr v2.3.4
       Compiling log v0.4.14
       Compiling serde v1.0.125
       Compiling cc v1.0.67
       Compiling pin-project-lite v0.2.6
       Compiling itoa v0.4.7
       Compiling getrandom v0.2.2
       Compiling bytes v1.0.1
       Compiling spin v0.5.2
       Compiling untrusted v0.7.1
       Compiling proc-macro-hack v0.5.19
       Compiling once_cell v1.7.2
       Compiling futures-core v0.3.13
       Compiling lazy_static v1.4.0
       Compiling proc-macro-nested v0.1.7
       Compiling ryu v1.0.5
       Compiling hashbrown v0.9.1
       Compiling matches v0.1.8
       Compiling typenum v1.13.0
       Compiling fnv v1.0.7
       Compiling adler v1.0.2
       Compiling futures-task v0.3.13
       Compiling slab v0.4.2
       Compiling byteorder v1.4.3
       Compiling encoding_rs v0.8.28
       Compiling futures-io v0.3.13
       Compiling httparse v1.3.6
       Compiling tinyvec_macros v0.1.0
       Compiling pkg-config v0.3.19
       Compiling futures-sink v0.3.13
       Compiling pin-utils v0.1.0
       Compiling regex-syntax v0.6.23
       Compiling base64 v0.13.0
       Compiling ppv-lite86 v0.2.10
       Compiling percent-encoding v2.1.0
       Compiling bitflags v1.2.1
       Compiling crc32fast v1.2.1
       Compiling try-lock v0.2.3
       Compiling serde_json v1.0.64
       Compiling unicode-segmentation v1.7.1
       Compiling ucd-trie v0.1.3
       Compiling void v1.0.2
       Compiling tower-service v0.3.1
       Compiling gimli v0.23.0
       Compiling termcolor v1.1.2
       Compiling quick-error v1.2.3
       Compiling camino v1.0.4
       Compiling winapi v0.3.9
       Compiling unicode-width v0.1.8
       Compiling httpdate v0.3.2
       Compiling remove_dir_all v0.5.3
       Compiling plain v0.2.3
       Compiling cbindgen v0.18.0
       Compiling either v1.6.1
       Compiling rustc-demangle v0.1.18
       Compiling vec_map v0.8.2
       Compiling ascii v0.9.3
       Compiling platforms v1.1.0
       Compiling object v0.23.0
       Compiling mime v0.3.16
       Compiling anyhow v1.0.40
       Compiling ansi_term v0.11.0
       Compiling strsim v0.8.0
       Compiling ipnet v2.3.0
       Compiling cpuid-bool v0.1.2
       Compiling linked-hash-map v0.5.4
       Compiling podio v0.1.7
       Compiling opaque-debug v0.3.0
       Compiling quoted_printable v0.4.3
       Compiling base64 v0.12.3
       Compiling same-file v1.0.6
       Compiling bytesize v1.0.1
       Compiling configparser v2.0.0
       Compiling fs-err v2.5.0
       Compiling glob v0.3.0
       Compiling shlex v1.0.0
       Compiling unicase v2.6.0
       Compiling proc-macro-error-attr v1.0.4
       Compiling generic-array v0.14.4
       Compiling proc-macro-error v1.0.4
       Compiling tokio v1.4.0
       Compiling indexmap v1.6.2
       Compiling miniz_oxide v0.4.4
       Compiling num-traits v0.2.14
       Compiling num-integer v0.1.44
       Compiling tracing-core v0.1.17
       Compiling futures-channel v0.3.13
       Compiling unicode-bidi v0.3.5
       Compiling http v0.2.4
       Compiling ring v0.16.20
       Compiling tinyvec v1.2.0
       Compiling base64 v0.10.1
       Compiling form_urlencoded v1.0.1
       Compiling bzip2-sys v0.1.10+1.0.8
       Compiling unreachable v1.0.0
       Compiling pest v2.1.3
       Compiling heck v0.3.2
       Compiling humantime v1.3.0
       Compiling textwrap v0.11.0
       Compiling addr2line v0.14.1
       Compiling walkdir v2.3.2
       Compiling tracing v0.1.25
       Compiling unicode-normalization v0.1.17
       Compiling num_cpus v1.13.0
       Compiling atty v0.2.14
       Compiling time v0.1.43
       Compiling socket2 v0.4.0
       Compiling xattr v0.2.2
       Compiling filetime v0.2.14
       Compiling dirs-sys v0.3.5
       Compiling rpassword v5.0.1
       Compiling semver-parser v0.10.2
       Compiling quote v1.0.9
       Compiling aho-corasick v0.7.15
       Compiling combine v3.8.1
       Compiling mio v0.7.11
       Compiling want v0.3.0
       Compiling http-body v0.4.1
       Compiling platform-info v0.1.0
       Compiling mime_guess v2.0.3
       Compiling charset v0.1.2
       Compiling clap v2.33.3
       Compiling rand_core v0.6.2
       Compiling uuid v0.8.2
       Compiling idna v0.2.2
       Compiling tar v0.4.33
       Compiling dirs v3.0.1
       Compiling regex v1.4.5
       Compiling backtrace v0.3.56
       Compiling flate2 v1.0.20
       Compiling bzip2 v0.3.3
       Compiling block-buffer v0.9.0
       Compiling digest v0.9.0
       Compiling mailparse v0.13.2
       Compiling rand_chacha v0.3.0
       Compiling url v2.2.1
       Compiling webpki v0.21.4
       Compiling sct v0.6.0
       Compiling os_type v2.2.0
       Compiling env_logger v0.7.1
       Compiling zip v0.5.6
       Compiling chrono v0.4.19
       Compiling sha2 v0.9.3
       Compiling rand v0.8.3
       Compiling tokio-util v0.6.5
       Compiling rustls v0.19.0
       Compiling webpki-roots v0.21.1
       Compiling pretty_env_logger v0.4.0
       Compiling toml_edit v0.2.0
       Compiling tempfile v3.2.0
       Compiling futures-macro v0.3.13
       Compiling pin-project-internal v1.0.6
       Compiling derivative v2.2.0
       Compiling scroll_derive v0.10.5
       Compiling structopt-derive v0.4.14
       Compiling thiserror-impl v1.0.24
       Compiling tokio-rustls v0.22.0
       Compiling scroll v0.10.2
       Compiling futures-util v0.3.13
       Compiling pin-project v1.0.6
       Compiling goblin v0.3.4
       Compiling thiserror v1.0.24
       Compiling structopt v0.3.21
       Compiling h2 v0.3.2
       Compiling toml v0.5.8
       Compiling serde_urlencoded v0.7.0
       Compiling semver v0.11.0
       Compiling cargo-platform v0.1.1
       Compiling hyper v0.14.5
       Compiling cargo_metadata v0.13.1
       Compiling proc-macro-crate v0.1.5
       Compiling human-panic v1.0.3
       Compiling num_enum_derive v0.5.1
       Compiling num_enum v0.5.1
       Compiling llvm-bitcode v0.1.2
       Compiling fat-macho v0.4.2
       Compiling hyper-rustls v0.22.1
       Compiling reqwest v0.11.2
       Compiling maturin v0.10.3 (/tmp/pip-install-aejl9q1c/maturin_87a7ed76948c462d81a3090eb63e4442)
    error: could not compile `maturin`
  
    To learn more, run the command again with --verbose.
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
        return _build_backend().build_wheel(wheel_directory, config_settings,
      File "/tmp/pip-build-env-8f53uovb/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 216, in build_wheel
        return self._build_with_temp_dir(['bdist_wheel'], '.whl',
      File "/tmp/pip-build-env-8f53uovb/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
        self.run_setup()
      File "/tmp/pip-build-env-8f53uovb/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 96, in <module>
        setup(
      File "/tmp/pip-build-env-8f53uovb/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-8f53uovb/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 335, in run
        self.run_command('install')
      File "/usr/local/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "setup.py", line 72, in run
        metadata = json.loads(subprocess.check_output(cargo_args).splitlines()[-2])
      File "/usr/local/lib/python3.9/subprocess.py", line 424, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['/usr/local/bin/cargo', 'rustc', '--bin', 'maturin', '--message-format=json', '--', '-C', 'link-arg=-s']' returned non-zero exit status 101.
    ----------------------------------------
    ERROR: Failed building wheel for maturin
  Failed to build maturin
  ERROR: Could not build wheels for maturin which use PEP 517 and cannot be installed directly
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/50/3d/31803e13b4ddd271047b6a62366bd4abd2cb08dc55a0b47a8b3b2dc2dbc7/orjson-3.5.2.tar.gz#sha256=f385253a6ddac37ea422ec2c0d35772b4f5bf0dc0803ce44543bf7e530423ef8 (from https://pypi.org/simple/orjson/) (requires-python:>=3.6). Command errored out with exit status 1: /usr/local/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-_cqsq37c/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- maturin==0.10.3 Check the logs for full command output.
  Using cached orjson-3.5.1.tar.gz (659 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-g5iler14/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- maturin==0.9.0
       cwd: None
  Complete output (244 lines):
```

**Comment by konstin** [comment]
Could you try with the latest prerelease? At least [CI passes for FreeBSD 12.2](https://github.com/PyO3/maturin/runs/2453851926) with the latest prerelease

**Comment by syleishere** [comment]
Trying with:
pip3.9 install git+https://github.com/PyO3/maturin@v0.10.4-beta.2

Let you know when it completes....

**Comment by syleishere** [comment]
Ok that built fine:
```
# pip3.9 install git+https://github.com/PyO3/maturin@v0.10.4-beta.2
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/include/python3.9/UNKNOWN
sysconfig: /usr/local/include/python3.9
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Collecting git+https://github.com/PyO3/maturin@v0.10.4-beta.2
  Cloning https://github.com/PyO3/maturin (to revision v0.10.4-beta.2) to /tmp/pip-req-build-9httiaxj
  Running command git clone -q https://github.com/PyO3/maturin /tmp/pip-req-build-9httiaxj
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting toml~=0.10.0
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Building wheels for collected packages: maturin
  Building wheel for maturin (PEP 517) ... done
  Created wheel for maturin: filename=maturin-0.10.4b2-cp39-cp39-freebsd_12_2_release_p6_amd64.whl size=6668097 sha256=1998b2fb8533623a7824af44a6f706951a93dc833073610bf22b64efa9413b6e
  Stored in directory: /tmp/pip-ephem-wheel-cache-g_p_dzmg/wheels/27/96/01/40a68fa269fdbfbcf99e83f8d6df4e67cfaf00c82b94e1e8b0
Successfully built maturin
Installing collected packages: toml, maturin
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/include/python3.9/UNKNOWN
sysconfig: /usr/local/include/python3.9
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Successfully installed maturin-0.10.4b2 toml-0.10.2
```

**Comment by konstin** [comment]
@messense If you want you can release the current main branch as v0.10.4

**Comment by messense** [comment]
> @messense If you want you can release the current main branch as v0.10.4

Done.

Closing as resolved, thanks for confirming @syleishere
