### ISSUE TITLE
PyPy builds of rust-numpy started failing with Maturin 0.12.13

### ISSUE THREAD

**Issue by adamreichold** [PyO3/maturin#882]
### Bug Description

CI builds of rust-numpy using PyPy started failing using Maturin 0.12.13 with the following panic message

```
  thread 'main' panicked at 'assertion failed: `(left == right)`
    left: `2`,
   right: `1`', src/main.rs:292:13
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
     2: core::panicking::assert_failed_inner
     3: core::panicking::assert_failed
     4: maturin::run
     5: maturin::main
```

### Your Python version (`python -V`)

PyPy 7.3.9

### Your pip version (`pip -V`)

?

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

https://github.com/PyO3/rust-numpy/runs/6155671160?check_suite_focus=true

**Comment by messense** [comment]
https://github.com/PyO3/maturin/blob/467c3dd5a87b321b0344fceb1ae90b12cef0a758/src/main.rs#L292

So somehow it builds multiple wheels instead of just one.

**Comment by adamreichold** [comment]
The logs contain

```
🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.7
  🐍 Not using a specific python interpreter
  📦 Built wheel for abi3 Python ≥ 3.7 to /home/runner/work/rust-numpy/rust-numpy/examples/simple/target/wheels/rust_ext-0.1.0-cp37-abi3-linux_x86_64.whl
  ⚠️ Warning: PyPy does not yet support abi3 so the build artifacts will be version-specific. See https://foss.heptapod.net/pypy/pypy/-/issues/3397 for more information.
  📦 Built wheel for PyPy 3.7 to /home/runner/work/rust-numpy/rust-numpy/examples/simple/target/wheels/rust_ext-0.1.0-pp37-pypy37_pp73-linux_x86_64.whl
```

so as `abi3` does not really make sense of PyPy, it seems to build both `rust_ext-0.1.0-cp37-abi3-linux_x86_64.whl` and `rust_ext-0.1.0-pp37-pypy37_pp73-linux_x86_64.whl`.

**Comment by messense** [comment]
It's kinda odd that it seems to work with `maturin build`: https://github.com/PyO3/maturin/runs/6153657419?check_suite_focus=true

I'm trying to reproduce the `maturin pep517 build-wheel` in #883 .

**Comment by adamreichold** [comment]
Seems to work: https://github.com/PyO3/rust-numpy/runs/6162637050?check_suite_focus=true

Thank you for investigating and resolving this so quickly!

**Comment by messense** [comment]
v0.12.14 should be out soon: https://github.com/PyO3/maturin/actions/runs/2223028291
